// leave off @2x/@3x
const images = {
	iconListActive: require('../Images/Icons/list_active.png'),
	iconListInactive: require('../Images/Icons/list_inactive.png'),
	iconProfileActive: require('../Images/Icons/profile_active.png'),
	iconProfileInactive: require('../Images/Icons/profile_inactive.png'),
	iconRadarActive: require('../Images/Icons/radar_active.png'),
	iconRadarInactive: require('../Images/Icons/radar_inactive.png'),
	iconArrowLeft: require('../Images/Icons/arrow_left.png'),
	iconArrowRight: require('../Images/Icons/arrow_right.png'),
	launch: require('../Images/launch-icon.png'),
	ignite: require('../Images/ignite_logo.png'),
	igniteClear: require('../Images/ignite-logo-transparent.png'),
	iconLock: require('../Images/Icons/lock-icon.png'),
	iconLeading: require('../Images/Icons/leading-icon.png'),
	eye: require('../Images/Icons/eye.png'),
	eyeOff: require('../Images/Icons/eye-off.png'),
	clear: require('../Images/Icons/clear.png'),
	opacityFrame: require('../Images/opacity-frame.png'),
	iconPlus: require('../Images/Icons/icon-plus.png'),
	iconProfileOn: require('../Images/Icons/icon-profile-on.png'),
	iconProfileOff: require('../Images/Icons/icon-profile-off.png'),
	iconQrCodeOn: require('../Images/Icons/icon-qr-code-on.png'),
	iconQrCodeOff: require('../Images/Icons/icon-qr-code-off.png'),
	iconWallet: require('../Images/Icons/icon-wallet.png'),
	iconArrowLeftBlue: require('../Images/Icons/icon-arrow-left-blue.png'),
	iconArrowLeftGreen: require('../Images/Icons/icon-arrow-left-green.png'),
	iconArrowLeftWhite: require('../Images/Icons/icon-arrow-left-white.png'),
	iconCard: require('../Images/Icons/icon-card.png'),
	iconHomeOn: require('../Images/Icons/icon-home-on.png'),
	iconHomeOff: require('../Images/Icons/icon-home-off.png'),
	iconMasterCard: require('../Images/Icons/icon-mastercard.png')
};

export default images;
